### PR TITLE
changes the name of run/debug configurations to fishstrap

### PR DESCRIPTION
**Pull request by mikeywhiston**
changes the configurations in rider / vsc / IDEs for c# to correctly identify Fishstrap instead of Bloxstrap
it is not satisfactory to underestimate the power of the 🐟
image

### CODE REVIEW

**Comment by mikeywhiston** [comment]
i have 0 idea how it changed that many files but it works and builds so

**Comment by mikeywhiston** [comment]
image

**Comment by returnrqt** [comment]
Will merging from Bloxstrap repository work fine with project name change?

**Comment by mikeywhiston** [comment]
you hold a very good point
ill revert this back to solely a run/debug change rather than a massive solution change

**Comment by mikeywhiston** [comment]
next commit in like 30 seconds

**Comment by mikeywhiston** [comment]
hope and pray

**Comment by mikeywhiston** [comment]
ok this should actually work now

**Comment by returnrqt** [comment]
I'll review it tomorrow.

**Pull request merged**
